### ISSUE TITLE
Register models in JSONParser automatically

### ISSUE THREAD

**Issue by skovmand** [wise-home/wise_homex#114]
To continue on the automatic api generation, it would be nice if we didn't need to fill in the types to models map in JSONParser. This can be filled in along with the automatic api generation.

**Comment by lasseebert** [comment]
Note that endpoints and models does not always have a one-to-one relationship. And some endpoints have the same models (e.g. /account-payments might not be the only path that deals with account payments).

Perhaps add a separate section in the api_config.exs that maps types to models and have a separate set of functions and macros to deal with those?
