### ISSUE TITLE
Consistency and less duplication

### ISSUE THREAD

**Issue by lasseebert** [wise-home/wise_homex#48]
We should consider:

* The APIClient functions are not consistent. Some take `attrs` and `rels` as maps and some take individual attributes and relations. It should be consistent, so that it is possible to guess how an api_function works.
* When adding a new api_function, it must be added in the behaviour, in `WiseHomex`, in the implementaion and in the mock. We can probably do this smarter with less duplication.

**Comment by lasseebert** [comment]
* [ ] Only define endpoints once
* [ ] Similar endpoints should have similar definition. E.g. all index-endpoints behave the same way.
* [ ] The json-api type of a model should be defined on the model
* [ ] When requesting with `relationships`, it should not be needed to spell out the entire data identifier. Do something smarter.

**Comment by lasseebert** [comment]
Putting this on hold for now. I tried to do a quick prototype and have a good idea what we should do, but it would take a lot of time to implement it.

* Define all endpoints as config (data) somewhere, e.g. as a module attribute. Each endpoint has enough information to make a request. E.g. all `:index` endpoint share behaviour. We can then define all endpoints here, and the mock and impl will be called with general functions with every information they need, e.g. `api_client().get(config, :get_accounts, "/accounts", options)`
* Move jsonapi type to models. Each model should know about relations, so we can parse e.g. `%{admin: 5, household: 42}` to `rels` in an api function.
* No more `query`. Instead it should be able to call with `[filter: %{name: "John"}, sort: "-name", filter: %{admin_id: 5, household_id: 2}, include: [household: [:address, :tenants]]]` etc.

**Comment by skovmand** [comment]
#107 was just merged, which introduces automatic api client function generation from config data. This will in time ensure consistency between all standard REST api calls from `wise_homex`. For now only the `expense` is generated automatically, and we will use the automatic generation for all future endpoints.

We should move as much of our current api as we can to the data-based format.

**Comment by skovmand** [comment]
@lasseebert Can I close this issue and create a new issue for moving existing api functions to the data-based format?

There are several other good ideas in this issue, but if we don't have any plans for implementing them now, I think we can close the issue and leave it for reference. What do you think?

**Comment by lasseebert** [comment]
@skovmand: Fine by me :+1:
