### ISSUE TITLE
Set up automatic tests on CircleCI

### ISSUE THREAD

**Issue by skovmand** [wise-home/wise_homex#8]
This repository should check the code with the following checks:

```
mix test
mix credo
mix dialyzer
mix format --check-formatted
```

We could do it using CircleCI or perhaps using GitHub actions?

**Comment by skovmand** [comment]
@lasseebert Is this something for you? Could be nice to get done, and I know that you know the tools.

**Comment by lasseebert** [comment]
@skovmand: Yep :+1:
